name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: Run ESLint for code linting
        run: npm run lint > lint_errors.txt || true

      - name: Display ESLint errors
        run: cat lint_errors.txt
