name: Code Review 

on:
  pull_request:
    branches:
      - main

jobs:
  code_review:
    name: Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Linters
        run: npm run lint
     
      - name: Code Analysis
        # run: npm run analyze if in scripts code analyzer like sonar mentioned

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Analyze code 
        uses: github/codeql-action/analyze@v1 

      - name: Feedback
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const reviewComment = `Thank you for the pull request! Here's the feedback based on the code review: ...`;
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: reviewComment,
              event: 'COMMENT'
            });
