name: Code Review Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

     # - name: Run Super-Linter
      #  uses: github/super-linter@v3
        #env:
         # DEFAULT_BRANCH: main
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install istanbul to check code coverage in code standards
        run: npm install istanbul

      - name: Run instanbul
        run: npx istanbul cover run.js

     # - name: Run Snyk security scan
      #  run: npx snyk test --all-projects
