name: Code Review Workflow

on:
  push:
    branches: [ main ]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Run ESLint
        run: npm run lint

      - name: Install istanbul to check code coverage in code standards
        run: npm install istanbul

      - name: Run instanbul
        run: npm run run.js

     # - name: Run Snyk security scan
      #  run: npx snyk test --all-projects

      - name: Comment on pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const comment = 'Code review checks completed. Please review the results.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
