name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: release_notes
        run: |
          git log --pretty=format:"- %s" > release_notes.txt
          cat release_notes.txt

      - name: Create or Append to CHANGELOG.md
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "${{ steps.release_notes.outputs.notes }}" >> CHANGELOG.md
            cat CHANGELOG.md
          else
            echo "${{ steps.release_notes.outputs.notes }}" > CHANGELOG.md
            cat CHANGELOG.md
          fi
