name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: release_notes
        run: |
          git log --pretty=format:"- %s" > release_notes.txt
          cat release_notes.txt

      - name: Create or Append to CHANGELOG.md
        run: |
          if [ -f "CHANGELOG.md" ]; then
            cat release_notes.txt >> CHANGELOG.md
            cat CHANGELOG.md
          else
            cat release_notes.txt >> CHANGELOG.md
            cat CHANGELOG.md
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md with release notes"
          git push
