name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Deploying to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './src' 
          github-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Echo Deployment Status
        run: echo "Deployment to Netlify completed successfully"
