name: Documentation Generation

on:
  push:
    branches:
      - main  

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  
      
      - name: Install dependencies
        run: npm install

      - name: Create Docs Directory
        run: mkdir -p docs
      
      - name: Generate Documentation
        run: npx jsdoc-to-markdown ./src/*.js > ./docs/documentation.md
