name: Documentation Generation

on:
  push:
    branches:
      - main  

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  
      
      - name: Install dependencies
        run: npm install

      - name: Create Docs Directory
        run: mkdir -p docs
      
      - name: Generate Documentation
        run: npx jsdoc-to-markdown ./src/*.js > ./docs/documentation.md

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Generate documentation"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-docs:
    runs-on: ubuntu-latest
    needs: generate-docs 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Create Docs Directory
        run: mkdir -p docs

      - name: Copy Documentation Files
        run: cp -r ${{ github.workspace }}/docs/* .

      - name: Commit Documentation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy documentation to GitHub Pages"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages 
